### ISSUE TITLE
antiScreenshot

### ISSUE THREAD

**Issue by be59okuz** [FatihAvdan/metin2-opencv-bot#2]
Oynadığım sunucuda antiScreenshot mevcut herhangi bir şekilde ekran görüntüsü alacak dahi olsam programlar oyundan görüntü alamıyor bunun için bir çözüm var mıdır?

**Comment by FatihAvdan** [comment]
daha önce karşılaşmadım hiç discord gel bakalım https://discord.gg/SXeJfBUZ
